# Generated by Django 5.0.6 on 2024-05-21 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('dispatched', 'Dispatched'), ('terminal', 'Terminal'), ('loading', 'Loading'), ('shipped', 'Shipped'), ('unloaded', 'Unloaded'), ('archived', 'Archived')], default='new', max_length=10)),
                ('date_purchase', models.DateField()),
                ('date_warehouse', models.DateField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('date_booking', models.DateField(blank=True, null=True)),
                ('data_container', models.DateField(blank=True, null=True)),
                ('date_unloaded', models.DateField(blank=True, null=True)),
                ('auto', models.CharField(max_length=255)),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('lot', models.CharField(max_length=255, unique=True)),
                ('account', models.CharField(max_length=255)),
                ('auction', models.CharField(max_length=255)),
                ('bos', models.FileField(upload_to='bos/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photo_a', models.ImageField(upload_to='photos/')),
                ('keys', models.BooleanField()),
                ('photo_d', models.ImageField(upload_to='photos/')),
                ('photo_w', models.ImageField(upload_to='photos/')),
                ('video', models.FileField(upload_to='videos/')),
                ('title', models.FileField(upload_to='titles/')),
                ('line', models.CharField(max_length=255)),
                ('booking_number', models.CharField(max_length=255)),
                ('container', models.CharField(max_length=255)),
                ('ata_data', models.DateField(blank=True, null=True)),
                ('photo_l', models.ImageField(upload_to='photos/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_logistics.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_logistics.customer')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_logistics.warehouse')),
            ],
        ),
    ]
