# Generated by Django 5.0.6 on 2024-05-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_logistics', '0003_auction_alter_lot_auction'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='url',
            field=models.URLField(default='http://example.com'),
        ),
    ]
