# Generated by Django 5.0.6 on 2024-05-27 14:51

import car_logistics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_logistics', '0007_alter_lot_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='bos',
            field=models.FileField(upload_to=car_logistics.models.unique_upload_path),
        ),
        migrations.AlterField(
            model_name='lot',
            name='photo_a',
            field=models.ImageField(upload_to=car_logistics.models.unique_upload_path),
        ),
        migrations.AlterField(
            model_name='lot',
            name='photo_d',
            field=models.ImageField(upload_to=car_logistics.models.unique_upload_path),
        ),
        migrations.AlterField(
            model_name='lot',
            name='photo_l',
            field=models.ImageField(upload_to=car_logistics.models.unique_upload_path),
        ),
        migrations.AlterField(
            model_name='lot',
            name='photo_w',
            field=models.ImageField(upload_to=car_logistics.models.unique_upload_path),
        ),
        migrations.AlterField(
            model_name='lot',
            name='title',
            field=models.FileField(upload_to=car_logistics.models.unique_upload_path),
        ),
        migrations.AlterField(
            model_name='lot',
            name='video',
            field=models.FileField(upload_to=car_logistics.models.unique_upload_path),
        ),
    ]
