# Generated by Django 5.0.6 on 2024-06-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_logistics', '0012_file_image_remove_lot_bos_remove_lot_photo_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='bos',
            field=models.ManyToManyField(related_name='bos_files', to='car_logistics.file'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='photo_a',
            field=models.ManyToManyField(related_name='photo_a_images', to='car_logistics.image'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='photo_d',
            field=models.ManyToManyField(blank=True, related_name='photo_d_images', to='car_logistics.image'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='photo_l',
            field=models.ManyToManyField(blank=True, related_name='photo_l_images', to='car_logistics.image'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='photo_w',
            field=models.ManyToManyField(blank=True, related_name='photo_w_images', to='car_logistics.image'),
        ),
    ]
