# Generated by Django 5.0.6 on 2024-06-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_logistics', '0013_alter_lot_bos_alter_lot_photo_a_alter_lot_photo_d_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='bos',
            field=models.ManyToManyField(related_name='bos_lots', to='car_logistics.file'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='photo_a',
            field=models.ManyToManyField(related_name='photo_a_lots', to='car_logistics.image'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='photo_d',
            field=models.ManyToManyField(blank=True, related_name='photo_d_lots', to='car_logistics.image'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='photo_l',
            field=models.ManyToManyField(blank=True, related_name='photo_l_lots', to='car_logistics.image'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='photo_w',
            field=models.ManyToManyField(blank=True, related_name='photo_w_lots', to='car_logistics.image'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='title',
            field=models.ManyToManyField(blank=True, related_name='title_lots', to='car_logistics.file'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='video',
            field=models.ManyToManyField(blank=True, related_name='video_lots', to='car_logistics.file'),
        ),
    ]
