# Generated by Django 5.0.6 on 2024-06-07 08:09

import car_logistics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_logistics', '0015_remove_lot_video_remove_lot_title_remove_lot_bos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=car_logistics.models.unique_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=car_logistics.models.unique_upload_path)),
            ],
        ),
        migrations.RemoveField(
            model_name='lot',
            name='bos',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='photo_a',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='photo_d',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='photo_l',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='photo_w',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='title',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='video',
        ),
        migrations.AddField(
            model_name='lot',
            name='bos',
            field=models.ManyToManyField(blank=True, related_name='bos_lots', to='car_logistics.document'),
        ),
        migrations.AddField(
            model_name='lot',
            name='photo_a',
            field=models.ManyToManyField(blank=True, related_name='photo_a_lots', to='car_logistics.image'),
        ),
        migrations.AddField(
            model_name='lot',
            name='photo_d',
            field=models.ManyToManyField(blank=True, related_name='photo_d_lots', to='car_logistics.image'),
        ),
        migrations.AddField(
            model_name='lot',
            name='photo_l',
            field=models.ManyToManyField(blank=True, related_name='photo_l_lots', to='car_logistics.image'),
        ),
        migrations.AddField(
            model_name='lot',
            name='photo_w',
            field=models.ManyToManyField(blank=True, related_name='photo_w_lots', to='car_logistics.image'),
        ),
        migrations.AddField(
            model_name='lot',
            name='title',
            field=models.ManyToManyField(blank=True, related_name='title_lots', to='car_logistics.document'),
        ),
        migrations.AddField(
            model_name='lot',
            name='video',
            field=models.ManyToManyField(blank=True, related_name='video_lots', to='car_logistics.document'),
        ),
    ]
