# Generated by Django 5.0.6 on 2024-06-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_logistics', '0017_remove_lot_bos_remove_lot_photo_a_remove_lot_photo_d_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='lot',
        ),
        migrations.RemoveField(
            model_name='image',
            name='lot',
        ),
        migrations.AddField(
            model_name='lot',
            name='bos',
            field=models.ManyToManyField(blank=True, related_name='bos_lots', to='car_logistics.document'),
        ),
        migrations.AddField(
            model_name='lot',
            name='photo_a',
            field=models.ManyToManyField(blank=True, related_name='photo_a_lots', to='car_logistics.image'),
        ),
        migrations.AddField(
            model_name='lot',
            name='photo_d',
            field=models.ManyToManyField(blank=True, related_name='photo_d_lots', to='car_logistics.image'),
        ),
        migrations.AddField(
            model_name='lot',
            name='photo_l',
            field=models.ManyToManyField(blank=True, related_name='photo_l_lots', to='car_logistics.image'),
        ),
        migrations.AddField(
            model_name='lot',
            name='photo_w',
            field=models.ManyToManyField(blank=True, related_name='photo_w_lots', to='car_logistics.image'),
        ),
        migrations.AddField(
            model_name='lot',
            name='title',
            field=models.ManyToManyField(blank=True, related_name='title_lots', to='car_logistics.document'),
        ),
        migrations.AddField(
            model_name='lot',
            name='video',
            field=models.ManyToManyField(blank=True, related_name='video_lots', to='car_logistics.document'),
        ),
    ]
