# Generated by Django 5.0.6 on 2024-06-08 11:38

import car_logistics.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_logistics', '0019_document_lot_image_lot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='lot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='car_logistics.lot'),
        ),
        migrations.AlterField(
            model_name='image',
            name='lot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='car_logistics.lot'),
        ),
        migrations.RemoveField(
            model_name='lot',
            name='bos',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='photo_a',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='photo_d',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='photo_l',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='photo_w',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='title',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='video',
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=car_logistics.models.unique_upload_path)),
                ('lot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='car_logistics.lot')),
            ],
        ),
        migrations.AddField(
            model_name='lot',
            name='bos',
            field=models.FileField(blank=True, upload_to=car_logistics.models.unique_upload_path),
        ),
        migrations.AddField(
            model_name='lot',
            name='photo_a',
            field=models.ImageField(blank=True, upload_to=car_logistics.models.unique_upload_path),
        ),
        migrations.AddField(
            model_name='lot',
            name='photo_d',
            field=models.ImageField(blank=True, upload_to=car_logistics.models.unique_upload_path),
        ),
        migrations.AddField(
            model_name='lot',
            name='photo_l',
            field=models.ImageField(blank=True, upload_to=car_logistics.models.unique_upload_path),
        ),
        migrations.AddField(
            model_name='lot',
            name='photo_w',
            field=models.ImageField(blank=True, upload_to=car_logistics.models.unique_upload_path),
        ),
        migrations.AddField(
            model_name='lot',
            name='title',
            field=models.FileField(blank=True, upload_to=car_logistics.models.unique_upload_path),
        ),
        migrations.AddField(
            model_name='lot',
            name='video',
            field=models.FileField(blank=True, upload_to=car_logistics.models.unique_upload_path),
        ),
    ]
