# Generated by Django 5.0.6 on 2024-06-19 10:22

import car_logistics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_logistics', '0021_remove_image_lot_remove_video_lot_remove_lot_bos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='bos',
            field=models.FileField(blank=True, upload_to=car_logistics.models.unique_upload_path),
        ),
        migrations.AddField(
            model_name='lot',
            name='photo_a',
            field=models.ImageField(blank=True, upload_to=car_logistics.models.unique_upload_path),
        ),
        migrations.AddField(
            model_name='lot',
            name='photo_d',
            field=models.ImageField(blank=True, upload_to=car_logistics.models.unique_upload_path),
        ),
        migrations.AddField(
            model_name='lot',
            name='photo_l',
            field=models.ImageField(blank=True, upload_to=car_logistics.models.unique_upload_path),
        ),
        migrations.AddField(
            model_name='lot',
            name='photo_w',
            field=models.ImageField(blank=True, upload_to=car_logistics.models.unique_upload_path),
        ),
        migrations.AddField(
            model_name='lot',
            name='title',
            field=models.FileField(blank=True, upload_to=car_logistics.models.unique_upload_path),
        ),
        migrations.AddField(
            model_name='lot',
            name='video',
            field=models.FileField(blank=True, upload_to=car_logistics.models.unique_upload_path),
        ),
        migrations.DeleteModel(
            name='LotFile',
        ),
    ]
