# Generated by Django 5.0.6 on 2024-07-06 11:18

import car_logistics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_logistics', '0022_lot_bos_lot_photo_a_lot_photo_d_lot_photo_l_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='auto',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='lot',
            name='bos',
            field=models.FileField(blank=True, db_index=True, upload_to=car_logistics.models.unique_upload_path),
        ),
        migrations.AlterField(
            model_name='lot',
            name='lot',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='vin',
            field=models.CharField(db_index=True, max_length=17, unique=True),
        ),
    ]
