# Generated by Django 5.0.6 on 2024-07-06 12:35

import car_logistics.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_logistics', '0023_alter_lot_auto_alter_lot_bos_alter_lot_lot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=car_logistics.models.unique_upload_path)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='car_logistics.lot')),
            ],
        ),
    ]
