# Generated by Django 5.0.6 on 2024-07-06 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_logistics', '0024_lotfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LotFile',
        ),
    ]
